### ISSUE TITLE
Link to paper at bottom of README goes to 404

### ISSUE THREAD

**Issue by dtdannen** [azreasoners/NeurASP#5]
The link to the following paper at the bottom of the README goes to a 404 page.

http://peace.eas.asu.edu/joolee/papers/ste-ns-icml.pdf

**Comment by zhunyoung** [comment]
Thank you for pointing it out! It turns out that Dr. Joohyung Lee's research webpage http://peace.eas.asu.edu/joolee is down for some reason. We are working on it, and in the meantime, you can find this paper at its [PMLR page](https://proceedings.mlr.press/v162/yang22h.html) ([pdf](https://proceedings.mlr.press/v162/yang22h/yang22h.pdf)).

**Comment by azreasoners** [comment]
Thank you, the link is fixed now: https://azreasoners.github.io/ARG-webpage/pdfs/ste-ns-icml.pdf.
